# serverless.yml

service: Deploy-lambda

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2 # or your preferred region

functions:
  handler:
    handler: handler.handler
    events:
      - http:
          path: hello
          method: get
