service: Deploy-lambda

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2

functions:
  handler:
    handler: dist/handler.handler  # Ensure this matches the output file
    events:
      - http:
          path: hello
          method: get

custom:
  webpack:
    webpackConfig: webpack.config.js
