service: Deploy-lambda

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x # Adjust the runtime version as per your requirement
  region: us-west-2 # Specify your preferred AWS region
  # Add other provider configurations as needed

functions:
  handler:
    handler: handler.handler
    events:
      - http:
          path: hello
          method: get
