name: Deploy-lambda

on:
  push:
    branches:
      - master

jobs:
  lambda-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: Deploy Lambda
        run: |
          npx ncc build handle.js  
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=Deploy-lambda --zip-file=fileb://deploy.zip
      # - name: Install npm dependencies
      #   run: npm ci

      # - name: Deploy lambda function
      #   run: serverless deploy
