name: Deploy-lambda

on: 
  push:
    branches:
      - master

jobs:
  lambda-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
       
      - name: Install serverless globally
        run: npm install -g serverless
   
      - name: Configure AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Configure serverless authentication
        run: serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY

      - name: Install npm dependencies
        run: npm ci
  
      - name: Deploy lambda function
        run: serverless deploy
